# Generated by Django 2.2.6 on 2020-01-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
