# Generated by Django 2.2.6 on 2020-01-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teraz', '0004_getinfocms_maincms_pocms_przedcms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getinfocms',
            old_name='line',
            new_name='line_eng',
        ),
        migrations.RenameField(
            model_name='maincms',
            old_name='line',
            new_name='line_eng',
        ),
        migrations.RenameField(
            model_name='pocms',
            old_name='line',
            new_name='line_eng',
        ),
        migrations.RenameField(
            model_name='przedcms',
            old_name='line',
            new_name='line_eng',
        ),
        migrations.AddField(
            model_name='getinfocms',
            name='line_pl',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='maincms',
            name='line_pl',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pocms',
            name='line_pl',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='przedcms',
            name='line_pl',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
